services:
  storage:
    image: busybox
    volumes:
      - storage:/var/lib/mysql
  mysql:
    image: mysql:8.0.36
    ports:
      - 3307:3306
    volumes:
      - storage:/var/lib/mysql
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
volumes:
  storage:
