CREATE DATABASE IF NOT EXISTS `todo-db`;

CREATE TABLE IF NOT EXISTS `todo-db`.user (
    user_id CHAR(26) PRIMARY KEY COMMENT 'ユーザーID',
    name VARCHAR(255) NOT NULL COMMENT '名前',
    email VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
) ENGINE = InnoDB COMMENT 'ユーザー情報';

CREATE TABLE IF NOT EXISTS `todo-db`.todo (
    todo_id CHAR(26) PRIMARY KEY COMMENT 'ToDo ID',
    title VARCHAR(255) NOT NULL COMMENT 'タイトル',
    description TEXT NOT NULL COMMENT '説明',
    status ENUM('UNKNOWN', 'TODO', 'DOING', 'DONE') NOT NULL DEFAULT 'TODO' COMMENT 'ステータス',
    assign_user_id CHAR(26) NOT NULL COMMENT 'アサインユーザーID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    FOREIGN KEY (assign_user_id) REFERENCES `todo-db`.user (user_id)
) ENGINE = InnoDB  COMMENT 'ToDo情報';
