// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package todo

import (
	"github.com/kazuzaku-dev/todo-grpc-go/internal/todo/controller"
)

// Injectors from wire.go:

func InitUserService() (*controller.UserServiceHandler, error) {
	userServiceHandler := controller.NewUserServiceHandler()
	return userServiceHandler, nil
}

func InitTodoService() (*controller.ToDoServiceHandler, error) {
	toDoServiceHandler := controller.NewTodoServiceHandler()
	return toDoServiceHandler, nil
}
